# Generated by Django 4.2.17 on 2025-01-12 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FibonacciData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(50),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("result", models.IntegerField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
