# Generated by Django 4.2.17 on 2025-01-13 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fibonacci_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fibonaccidata",
            name="number",
            field=models.IntegerField(
                default=0,
                unique=True,
                validators=[
                    django.core.validators.MaxValueValidator(50),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
